pipeline {
    agent any
      stages { 
      stage('Checkout'){
        steps{
          echo 'Checking out from git'
          checkout scm
        }

     }
    stage('Install Dependencies'){
       steps{ 
       echo 'Installing dependencies'
       dir('BackendService'){
          sh 'npm ci'
       }
      }
     } 
  } 

}
