pipeline {
    agent any
      environment{
      APP_NAME='moodbuds'
      DOCKERFILE='Dockerfile'
      IMAGE_TAG="${BUILD_NAME}"
      }         
      stages {
      stage('Checkout'){
        steps{
          echo 'Checking out from git'
          checkout scm
        }
     }
    stage('Verify Environment'){
      steps{
       dir(BackendService){
       sh'''
       set -e 
       node --version
       npm  --version
       docker --version
       docker info
     }
  }
}
  stage('Build docker image'){
       steps{ 
       echo 'Building Docker image'
       dir('BackendService'){
          sh '''
          docker build \
          -f "${DOCKERFILE}"\
          -t "${APP_NAME}:${IMAGE_TAG}"\
          -t "${APP_NAME}:${GIT_COMMIT}"\
          .
       '''
       }
     }
   }
  } 
}

