services:
  moodbudsclient:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: moodbudsv1-frontend

    ports:
      - "8400:80"

    env_file:
      - .env

    networks:
      - NETWORK

    restart: unless-stopped

networks:
  NETWORK:
    external: true
























           
