pipeline {
y
    agent any

    environment {

    }  
    stages {
      stage('Scm  checkout'){


        }
       stage('Run tests'){


       }
       
       stage('Build docker images'){


        }
    }  
 
post{
 
    }
}
 
